main = ".worker-next/index.mjs"
name = "my-app"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
experimental_assets = { directory = ".worker-next/assets", binding = "ASSETS" }

[[kv_namespaces]]
binding = "BLOG_KV"
id = "87b4b84a88d64b6e86b33dba0257c1c7"

